INSERT INTO biblical_symbols (term, meaning, biblical_pattern, deeper_significance, categories, related_verses) VALUES
('Lion', 'Symbol of strength, royalty, and often divine power or judgment.', 'Appears as a protector (Psalm 91:13) and a destroyer (1 Peter 5:8). Jesus is called the Lion of Judah (Revelation 5:5).', 'Represents both destructive power and majestic authority; duality of nature.', '{"animal", "power"}', '{"Psalm 91:13", "1 Peter 5:8", "Revelation 5:5"}'),
('Lamb', 'Symbol of innocence, sacrifice, and gentleness. Often refers to Jesus Christ as the sacrificial Lamb of God.', 'Central to Passover (Exodus 12). Jesus as the Lamb who takes away the sin of the world (John 1:29).', 'Represents atonement, purity, and the ultimate sacrifice for sin.', '{"animal", "sacrifice"}', '{"Exodus 12:3", "John 1:29", "Revelation 7:17"}'),
('Water', 'Symbol of cleansing, life, spiritual refreshment, and judgment.', 'Used in creation (Genesis 1:2), flood (Genesis 6-9), baptism (Matthew 3:11), and living water (John 4:10).', 'Represents purification, sustenance, and the Holy Spirit; can also signify chaos or destruction.', '{"element", "life"}', '{"Genesis 1:2", "Matthew 3:11", "John 4:10", "Revelation 22:1"}'),
('Fire', 'Symbol of purification, divine presence, judgment, and testing.', 'Burning bush (Exodus 3:2), pillar of fire (Exodus 13:21), refining fire (Malachi 3:2), Holy Spirit (Acts 2:3).', 'Represents God\'s holiness, transformative power, and consuming wrath; can refine or destroy.', '{"element", "power"}', '{"Exodus 3:2", "Malachi 3:2", "Acts 2:3", "Hebrews 12:29"}'),
('Shepherd', 'Symbol of guidance, protection, care, and leadership. Often refers to God or Jesus as the Good Shepherd.', 'God as shepherd of Israel (Psalm 23). Jesus as the Good Shepherd (John 10:11). Leaders as shepherds of God\'s flock (1 Peter 5:2).', 'Represents divine provision, compassionate leadership, and spiritual nourishment.', '{"person", "leadership"}', '{"Psalm 23:1", "John 10:11", "1 Peter 5:2"}'),
('Light', 'Symbol of truth, purity, knowledge, and divine presence. Contrasted with darkness (evil, ignorance).', 'God is light (1 John 1:5). Jesus is the light of the world (John 8:12). Believers are children of light (Ephesians 5:8).', 'Represents revelation, moral uprightness, and the presence of God.', '{"element", "truth"}', '{"John 8:12", "1 John 1:5", "Ephesians 5:8"}'),
('Bread', 'Symbol of sustenance, life, and often refers to Jesus as the Bread of Life.', 'Manna in the wilderness (Exodus 16). Jesus feeding the multitudes (Matthew 14:13-21). The Lord\'s Supper (Matthew 26:26).', 'Represents physical and spiritual nourishment, and communion with God.', '{"food", "life"}', '{"Exodus 16:4", "John 6:35", "Matthew 26:26"}'),
('Vine', 'Symbol of Israel, spiritual connection, and fruitfulness. Jesus identifies Himself as the true vine.', 'Israel as God\'s vine (Psalm 80:8). Jesus as the true vine (John 15:1).', 'Represents the source of spiritual life, connection to God, and the production of spiritual fruit.', '{"plant", "life"}', '{"Psalm 80:8", "John 15:1", "Isaiah 5:1-7"}'),
('Rock', 'Symbol of strength, stability, refuge, and God\'s faithfulness. Often refers to God as a fortress.', 'God as a rock (Psalm 18:2). Peter as a rock (Matthew 16:18). Christ as the spiritual rock (1 Corinthians 10:4).', 'Represents unwavering support, divine protection, and a firm foundation.', '{"object", "strength"}', '{"Psalm 18:2", "Matthew 16:18", "1 Corinthians 10:4"}'),
('Crown', 'Symbol of royalty, victory, honor, and reward.', 'Kings wear crowns (2 Samuel 1:10). Crown of thorns (Matthew 27:29). Crown of life (James 1:12).', 'Represents authority, triumph over adversity, and eternal reward for faithfulness.', '{"object", "reward"}', '{"James 1:12", "Revelation 2:10", "1 Peter 5:4"}');