version: '3.8'

# ELK Stack + Filebeat for Centralized Logging
services:
  # Elasticsearch - Log storage and search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: deeper-bible-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./logging/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
    networks:
      - logging
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Logstash - Log processing and transformation
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: deeper-bible-logstash
    volumes:
      - ./logging/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logging/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - "5044:5044" # Beats input
      - "5000:5000" # TCP input
      - "9600:9600" # HTTP API
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    networks:
      - logging
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kibana - Log visualization and dashboards
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: deeper-bible-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=a7a6311933d3503b89bc2dbc36572c33a7a6311933d3503b89bc2dbc36572c33
    volumes:
      - ./logging/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kibana_data:/usr/share/kibana/data
    networks:
      - logging
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Filebeat - Log shipping from application
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: deeper-bible-filebeat
    user: root
    volumes:
      - ./logging/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeat_data:/usr/share/filebeat/data
      - ./logs:/var/logs:ro  # Application logs directory
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
      - LOGSTASH_HOST=logstash:5044
    networks:
      - logging
    depends_on:
      logstash:
        condition: service_healthy
    command: filebeat -e -strict.perms=false

  # Metricbeat - System and application metrics
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.11.0
    container_name: deeper-bible-metricbeat
    user: root
    volumes:
      - ./logging/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - metricbeat_data:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
    networks:
      - logging
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false

  # APM Server - Application performance monitoring
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.11.0
    container_name: deeper-bible-apm-server
    ports:
      - "8200:8200"
    volumes:
      - ./logging/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
    networks:
      - logging
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: apm-server -e -strict.perms=false

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  filebeat_data:
    driver: local
  metricbeat_data:
    driver: local

networks:
  logging:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16