# Filebeat Configuration for Deeper Bible API
filebeat.inputs:
  # Application logs from files
  - type: log
    enabled: true
    paths:
      - /var/logs/*.log
      - /var/logs/**/*.log
    fields:
      service: deeper-bible-api
      environment: ${ENV:production}
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after
    json.keys_under_root: true
    json.message_key: message

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    containers.ids:
      - '*'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

  # System logs
  - type: syslog
    enabled: true
    protocol.udp:
      host: "0.0.0.0:5140"

# Processors for log enhancement
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - fingerprint:
      fields: ["message", "@timestamp"]
      target_field: "@metadata.fingerprint"
  - timestamp:
      field: "@timestamp"
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2023-12-01T10:30:45.123Z'

# Output to Logstash for processing
output.logstash:
  hosts: ["${LOGSTASH_HOST:logstash:5044}"]
  worker: 1
  compression_level: 3
  escape_html: false

# Alternative direct output to Elasticsearch (comment out logstash output above)
# output.elasticsearch:
#   hosts: ["${ELASTICSEARCH_HOST:elasticsearch:9200}"]
#   index: "deeper-bible-logs-%{+yyyy.MM.dd}"
#   template.name: "deeper-bible-logs"
#   template.pattern: "deeper-bible-logs-*"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0600

# Monitoring
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["${ELASTICSEARCH_HOST:elasticsearch:9200}"]