# Prometheus Configuration for Deeper Bible API
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'deeper-bible-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'deeper-bible-api'

  # Application metrics
  - job_name: 'deeper-bible-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']
        labels:
          service: 'api'
          environment: 'production'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'api-prod'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
        labels:
          database: 'deeper_bible'
          environment: 'production'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
        labels:
          cache: 'main'
          environment: 'production'

  # Blackbox Exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.deeperbible.com/health
        - https://api.deeperbible.com/api/v1/status
        - https://staging.deeperbible.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115